name: Publish LuaRocks 🌔

on:
  release:
    types: [published]
  pull_request:

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"

      - name: Install LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks

      - name: Build and Upload Rock
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        run: |
          luarocks pack ./*.rockspec
          luarocks upload *.rockspec --api-key=$LUAROCKS_API_KEY --force
